<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

class CartSeeder extends Seeder
{
    public function run()
    {
        DB::table('carts')->insert([
            [
                'id' => 8,
                'user_id' => '3',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'yes',
                'coupon_id' => null,
                'shipping_address' => 'Chawkbazar,Chittagong',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'nxeio2qb',
                'delivery_time' => 'July 28, 2022, 15:55:00pm',
                'purchase_date' => '2022-07-20',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'user_id' => '3',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'yes',
                'coupon_id' => null,
                'shipping_address' => 'Chawkbazar,Chittagong',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'nxeio2qb',
                'delivery_time' => 'July 28, 2022, 15:55:00pm',
                'purchase_date' => '2022-07-20',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 10,
                'user_id' => '3',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'delivery',
                'coupon_id' => null,
                'shipping_address' => 'Chawkbazar,Chittagong',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => '5fi3xq0a',
                'delivery_time' => 'July 28, 2022, 15:55:00pm',
                'purchase_date' => '2022-07-20',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'user_id' => '3',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'delivery',
                'coupon_id' => null,
                'shipping_address' => 'Chawkbazar,Chittagong',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => '5fi3xq0a',
                'delivery_time' => 'July 28, 2022, 15:55:00pm',
                'purchase_date' => '2022-07-20',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'user_id' => '3',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'cancel',
                'coupon_id' => null,
                'shipping_address' => null,
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'd8p6efpn',
                'delivery_time' => 'July 29, 2022, 14:25:00pm',
                'purchase_date' => '2022-07-29',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'user_id' => '3',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'cancel',
                'coupon_id' => null,
                'shipping_address' => null,
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'd8p6efpn',
                'delivery_time' => 'July 29, 2022, 14:25:00pm',
                'purchase_date' => '2022-07-29',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'user_id' => '4',
                'product_id' => '5',
                'name' => 'Mango Cake',
                'price' => '540.00',
                'quantity' => '1',
                'subtotal' => '540.00',
                'product_order' => 'yes',
                'coupon_id' => null,
                'shipping_address' => '1st Block, Chawkbazar',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'fdrakgi2',
                'delivery_time' => 'August 10, 2022, 11:50:00am',
                'purchase_date' => '2022-08-10',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'user_id' => '4',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'yes',
                'coupon_id' => null,
                'shipping_address' => '1st Block, Chawkbazar',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'fdrakgi2',
                'delivery_time' => 'August 10, 2022, 11:50:00am',
                'purchase_date' => '2022-08-10',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'user_id' => '4',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'yes',
                'coupon_id' => null,
                'shipping_address' => '1st Block, Chawkbazar',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'fdrakgi2',
                'delivery_time' => 'August 10, 2022, 11:50:00am',
                'purchase_date' => '2022-08-10',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'user_id' => '4',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'approve',
                'coupon_id' => null,
                'shipping_address' => '1st Block, Chawkbazar',
                'pay_method' => 'Online Payment',
                'invoice_no' => 'mfgdr9yi',
                'delivery_time' => 'August 10, 2022, 11:50:00am',
                'purchase_date' => '2022-08-10',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 25,
                'user_id' => '4',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'approve',
                'coupon_id' => null,
                'shipping_address' => '1st Block, Chawkbazar',
                'pay_method' => 'Online Payment',
                'invoice_no' => 'mfgdr9yi',
                'delivery_time' => 'August 10, 2022, 11:50:00am',
                'purchase_date' => '2022-08-10',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 28,
                'user_id' => '3',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'yes',
                'coupon_id' => null,
                'shipping_address' => 'Chawkbazar,Chittagong',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'nxvdey9a',
                'delivery_time' => 'August 13, 2022, 19:40:00pm',
                'purchase_date' => '2022-08-13',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 29,
                'user_id' => '3',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'yes',
                'coupon_id' => null,
                'shipping_address' => 'Chawkbazar,Chittagong',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'nxvdey9a',
                'delivery_time' => 'August 13, 2022, 19:40:00pm',
                'purchase_date' => '2022-08-13',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 30,
                'user_id' => '3',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'delivery',
                'coupon_id' => null,
                'shipping_address' => 'Chawkbazar,Chittagong',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'lks4ibv2',
                'delivery_time' => 'August 13, 2022, 19:40:00pm',
                'purchase_date' => '2022-08-13',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 31,
                'user_id' => '3',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'delivery',
                'coupon_id' => null,
                'shipping_address' => 'Chawkbazar,Chittagong',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'lks4ibv2',
                'delivery_time' => 'August 13, 2022, 19:40:00pm',
                'purchase_date' => '2022-08-13',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 32,
                'user_id' => '3',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'cancel',
                'coupon_id' => null,
                'shipping_address' => null,
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'lprhfsx9',
                'delivery_time' => 'August 14, 2022, 10:20:00am',
                'purchase_date' => '2022-08-14',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 33,
                'user_id' => '3',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'cancel',
                'coupon_id' => null,
                'shipping_address' => null,
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'lprhfsx9',
                'delivery_time' => 'August 14, 2022, 10:20:00am',
                'purchase_date' => '2022-08-14',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 34,
                'user_id' => '3',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'approve',
                'coupon_id' => 'ED26',
                'shipping_address' => null,
                'pay_method' => 'Online Payment',
                'invoice_no' => 'oxw38fiv',
                'delivery_time' => 'August 14, 2022, 10:20:00am',
                'purchase_date' => '2022-08-14',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 35,
                'user_id' => '3',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'approve',
                'coupon_id' => 'ED26',
                'shipping_address' => null,
                'pay_method' => 'Online Payment',
                'invoice_no' => 'oxw38fiv',
                'delivery_time' => 'August 14, 2022, 10:20:00am',
                'purchase_date' => '2022-08-14',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 46,
                'user_id' => '3',
                'product_id' => '4',
                'name' => 'Klassy Cup Cake',
                'price' => '80.00',
                'quantity' => '1',
                'subtotal' => '80.00',
                'product_order' => 'approve',
                'coupon_id' => 'ED26',
                'shipping_address' => null,
                'pay_method' => 'Online Payment',
                'invoice_no' => 'dgqlewoi',
                'delivery_time' => 'September 1, 2022, 11:40:00am',
                'purchase_date' => '2022-09-01',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 47,
                'user_id' => '3',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'approve',
                'coupon_id' => 'ED26',
                'shipping_address' => null,
                'pay_method' => 'Online Payment',
                'invoice_no' => 'dgqlewoi',
                'delivery_time' => 'September 1, 2022, 11:40:00am',
                'purchase_date' => '2022-09-01',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 48,
                'user_id' => '3',
                'product_id' => '3',
                'name' => 'Blueberry Cake',
                'price' => '650.00',
                'quantity' => '1',
                'subtotal' => '650.00',
                'product_order' => 'yes',
                'coupon_id' => null,
                'shipping_address' => 'Chawkbazar,Chittagong',
                'pay_method' => 'Cash On Delivery',
                'invoice_no' => 'dsal9brw',
                'delivery_time' => 'September 5, 2022, 18:45:00pm',
                'purchase_date' => '2022-09-05',
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}